export const GROUP_LIST = [
	{
		id: 'bridge',
		label: 'Bridge',
		foldername: 'Bridge',
	},
	{
		id: 'engineering_bay',
		label: 'Engineering Bay',
		foldername: 'Engineering Bay',
	},
	{
		id: 'general_stratagems',
		label: 'General Stratagems',
		foldername: 'General Stratagems',
	},
	{
		id: 'hangar',
		label: 'Hangar',
		foldername: 'Hanger',
	},
	{
		id: 'orbital_cannons',
		label: 'Orbital Cannons',
		foldername: 'Orbital Cannons',
	},
	{
		id: 'patriotic_administration_center',
		label: 'Patriotic Administration Center',
		foldername: 'Patriotic Administration Center',
	},
	{
		id: 'robotics_workshop',
		label: 'Robotics Workshop',
		foldername: 'Robotics Workshop',
	},
];

export const ICON_LIST = [
	{
		id: 'hmg_emplacement',
		label: 'HMG Emplacement',
		group_id: 'bridge',
		filename: 'HMG Emplacement',
	},
	{
		id: 'orbital_ems_strike',
		label: 'Orbital EMS Strike',
		group_id: 'bridge',
		filename: 'Orbital EMS Strike',
	},
	{
		id: 'orbital_gas_strike',
		label: 'Orbital Gas Strike',
		group_id: 'bridge',
		filename: 'Orbital Gas Strike',
	},
	{
		id: 'orbital_precision_strike',
		label: 'Orbital Precision Strike',
		group_id: 'bridge',
		filename: 'Orbital Precision Strike',
	},
	{
		id: 'orbital_smoke_strike',
		label: 'Orbital Smoke Strike',
		group_id: 'bridge',
		filename: 'Orbital Smoke Strike',
	},
	{
		id: 'shield_generator_relay',
		label: 'Shield Generator Relay',
		group_id: 'bridge',
		filename: 'Shield Generator Relay',
	},
	{
		id: 'tesla_tower',
		label: 'Tesla Tower',
		group_id: 'bridge',
		filename: 'Tesla Tower',
	},
	{
		id: 'anti-personnel_minefield',
		label: 'Anti-Personnel Minefield',
		group_id: 'engineering_bay',
		filename: 'Anti-Personnel Minefield',
	},
	{
		id: 'arc_thrower',
		label: 'Arc Thrower',
		group_id: 'engineering_bay',
		filename: 'Arc Thrower',
	},
	{
		id: 'ballistic_shield_backpack',
		label: 'Ballistic Shield Backpack',
		group_id: 'engineering_bay',
		filename: 'Ballistic Shield Backpack',
	},
	{
		id: 'grenade_launcher',
		label: 'Grenade Launcher',
		group_id: 'engineering_bay',
		filename: 'Grenade Launcher',
	},
	{
		id: 'guard_dog_rover',
		label: 'Guard Dog Rover',
		group_id: 'engineering_bay',
		filename: 'Guard Dog Rover',
	},
	{
		id: 'incendiary_mines',
		label: 'Incendiary Mines',
		group_id: 'engineering_bay',
		filename: 'Incendiary Mines',
	},
	{
		id: 'laser_cannon',
		label: 'Laser Cannon',
		group_id: 'engineering_bay',
		filename: 'Laser Cannon',
	},
	{
		id: 'shield_generator_pack',
		label: 'Shield Generator Pack',
		group_id: 'engineering_bay',
		filename: 'Shield Generator Pack',
	},
	{
		id: 'supply_pack',
		label: 'Supply Pack',
		group_id: 'engineering_bay',
		filename: 'Supply Pack',
	},
	{
		id: 'hellbomb',
		label: 'Hellbomb',
		group_id: 'general_stratagems',
		filename: 'Hellbomb',
	},
	{
		id: 'orbital_illumination_flare',
		label: 'Orbital Illumination Flare',
		group_id: 'general_stratagems',
		filename: 'Orbital Illumination Flare',
	},
	{
		id: 'prospecting_drill',
		label: 'Prospecting Drill',
		group_id: 'general_stratagems',
		filename: 'Prospecting Drill',
	},
	{
		id: 'reinforce',
		label: 'Reinforce',
		group_id: 'general_stratagems',
		filename: 'Reinforce',
	},
	{
		id: 'resupply',
		label: 'Resupply',
		group_id: 'general_stratagems',
		filename: 'Resupply',
	},
	{
		id: 'seaf_artillery',
		label: 'SEAF Artillery',
		group_id: 'general_stratagems',
		filename: 'SEAF Artillery',
	},
	{
		id: 'seismic_probe',
		label: 'Seismic Probe',
		group_id: 'general_stratagems',
		filename: 'Seismic Probe',
	},
	{
		id: 'sos_beacon',
		label: 'SOS Beacon',
		group_id: 'general_stratagems',
		filename: 'SOS Beacon',
	},
	{
		id: 'super_earth_flag',
		label: 'Super Earth Flag',
		group_id: 'general_stratagems',
		filename: 'Super Earth Flag',
	},
	{
		id: 'upload_data',
		label: 'Upload Data',
		group_id: 'general_stratagems',
		filename: 'Upload Data',
	},
	{
		id: 'eagle_110mm_rocket_pods',
		label: 'Eagle 110MM Rocket Pods',
		group_id: 'hangar',
		filename: 'Eagle 110MM Rocket Pods',
	},
	{
		id: 'eagle_500kg_bomb',
		label: 'Eagle 500KG Bomb',
		group_id: 'hangar',
		filename: 'Eagle 500KG Bomb',
	},
	{
		id: 'eagle_airstrike',
		label: 'Eagle Airstrike',
		group_id: 'hangar',
		filename: 'Eagle Airstrike',
	},
	{
		id: 'eagle_cluster_bomb',
		label: 'Eagle Cluster Bomb',
		group_id: 'hangar',
		filename: 'Eagle Cluster Bomb',
	},
	{
		id: 'eagle_napalm_airstrike',
		label: 'Eagle Napalm Airstrike',
		group_id: 'hangar',
		filename: 'Eagle Napalm Airstrike',
	},
	{
		id: 'eagle_rearm',
		label: 'Eagle Rearm',
		group_id: 'hangar',
		filename: 'Eagle Rearm',
	},
	{
		id: 'eagle_smoke_strike',
		label: 'Eagle Smoke Strike',
		group_id: 'hangar',
		filename: 'Eagle Smoke Strike',
	},
	{
		id: 'eagle_strafing_run',
		label: 'Eagle Strafing Run',
		group_id: 'hangar',
		filename: 'Eagle Strafing Run',
	},
	{
		id: 'jump_pack',
		label: 'Jump Pack',
		group_id: 'hangar',
		filename: 'Jump Pack',
	},
	{
		id: 'orbital_120mm_he_barrage',
		label: 'Orbital 120MM HE Barrage',
		group_id: 'orbital_cannons',
		filename: 'Orbital 120MM HE Barrage',
	},
	{
		id: 'orbital_380mm_he_barrage',
		label: 'Orbital 380MM HE Barrage',
		group_id: 'orbital_cannons',
		filename: 'Orbital 380MM HE Barrage',
	},
	{
		id: 'orbital_airburst_strike',
		label: 'Orbital Airburst Strike',
		group_id: 'orbital_cannons',
		filename: 'Orbital Airburst Strike',
	},
	{
		id: 'orbital_gatling_barrage',
		label: 'Orbital Gatling Barrage',
		group_id: 'orbital_cannons',
		filename: 'Orbital Gatling Barrage',
	},
	{
		id: 'obital_laser',
		label: 'Orbital Laser',
		group_id: 'orbital_cannons',
		filename: 'Orbital Laser',
	},
	{
		id: 'orbital_railcannon_strike',
		label: 'Orbital Railcannon Strike',
		group_id: 'orbital_cannons',
		filename: 'Orbital Railcannon Strike',
	},
	{
		id: 'orbital_walking_barrage',
		label: 'Orbital Walking Barrage',
		group_id: 'orbital_cannons',
		filename: 'Orbital Walking Barrage',
	},
	{
		id: 'anti-materiel_rifle',
		label: 'Anti-Materiel Rifle',
		group_id: 'patriotic_administration_center',
		filename: 'Anti-Materiel Rifle',
	},
	{
		id: 'autocannon',
		label: 'Autocannon',
		group_id: 'patriotic_administration_center',
		filename: 'Autocannon',
	},
	{
		id: 'expendable_anti-tank',
		label: 'Expendable Anti-Tank',
		group_id: 'patriotic_administration_center',
		filename: 'Expendable Anti-Tank',
	},
	{
		id: 'flamethrower',
		label: 'Flamethrower',
		group_id: 'patriotic_administration_center',
		filename: 'Flamethrower',
	},
	{
		id: 'machine_gun',
		label: 'Machine Gun',
		group_id: 'patriotic_administration_center',
		filename: 'Machine Gun',
	},
	{
		id: 'railgun',
		label: 'Railgun',
		group_id: 'patriotic_administration_center',
		filename: 'Railgun',
	},
	{
		id: 'recoilless_rifle',
		label: 'Recoilless Rifle',
		group_id: 'patriotic_administration_center',
		filename: 'Recoilless Rifle',
	},
	{
		id: 'spear',
		label: 'Spear',
		group_id: 'patriotic_administration_center',
		filename: 'Spear',
	},
	{
		id: 'stalwart',
		label: 'Stalwart',
		group_id: 'patriotic_administration_center',
		filename: 'Stalwart',
	},
	{
		id: 'autocannon_sentry',
		label: 'Autocannon Sentry',
		group_id: 'robotics_workshop',
		filename: 'Autocannon Sentry',
	},
	{
		id: 'ems_mortar_sentry',
		label: 'EMS Mortar Sentry',
		group_id: 'robotics_workshop',
		filename: 'EMS Mortar Sentry',
	},
	{
		id: 'gatling_sentry',
		label: 'Gatling Sentry',
		group_id: 'robotics_workshop',
		filename: 'Gatling Sentry',
	},
	{
		id: 'guard_dog',
		label: 'Guard Dog',
		group_id: 'robotics_workshop',
		filename: 'Guard Dog',
	},
	{
		id: 'machine_gun_sentry',
		label: 'Machine Gun Sentry',
		group_id: 'robotics_workshop',
		filename: 'Machine Gun Sentry',
	},
	{
		id: 'mortar_sentry',
		label: 'Mortar Sentry',
		group_id: 'robotics_workshop',
		filename: 'Mortar Sentry',
	},
	{
		id: 'patriot_exosuit',
		label: 'Patriot Exosuit',
		group_id: 'robotics_workshop',
		filename: 'Patriot Exosuit',
	},
	{
		id: 'rocket_sentry',
		label: 'Rocket Sentry',
		group_id: 'robotics_workshop',
		filename: 'Rocket Sentry',
	},
]